sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t akshay/docker-react -f docketfile.dev .
  
script:
  - docker run akshay/docker-react npm run test -- --coverage
